name: icueMike
description: 'This website is for people who loves all things Path of Exile, Last Epoch, World of Warcraft and general everyday web coding.'
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: '/'
disqus: icuemike
email: icuemike@outlook.com
mailchimp-list: >-
  https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
  - _pages
permalink: '/:title/'
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
authors:
  icueMike:
    name: icueMike
    site: 'https://icuemike.github.io/site'
    avatar: /assets/images/icueMike.png
    bio: >-
      Hi, I am Mike, the author and developer of your reading about right now. I hope you my website!
    email: icuemike@outlook.com
    twitter: 'https://twitter.com/icuemike'
  jane:
    name: Jane
    site: 'https://www.wowthemes.net'
    avatar: /assets/images/avatar2.jpg
    bio: >-
      Blogger, fashionista, love to explore new ideas and write on my morning
      coffee!
    email: fakemail@gmail.com
    twitter: 'https://twitter.com/wowthemesnet'
defaults:
  - scope:
      path: _posts
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
  - scope:
      path: _pages
    values:
      layout: page
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
url: 'https://icuemike.github.io/site'
